package com.myspace.motor_reglas_kyt;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DocumentoOrigenFondos implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public DocumentoOrigenFondos() {
    }




}