package com.myspace.motor_reglas_kyt;

import com.myspace.motor_reglas_kyt.DocumentoOrigenFondos;
import java.util.Date;
import java.util.concurrent.TimeUnit;

rule "Verificar Vigencia Documento"
    ruleflow-group "vigencia-documentos"
    no-loop true
when
    $doc : DocumentoOrigenFondos(fechaFirma != null)
then
    Date ahora = new Date();
    long diff = ahora.getTime() - $doc.getFechaFirma().getTime();
    long meses = TimeUnit.DAYS.convert(diff, TimeUnit.MILLISECONDS) / 30;

    $doc.setVigente(meses < 6);

    update($doc);
end
